sonar.projectKey=flight-delay
sonar.projectName=FlightDelay
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,backend

sonar.exclusions=\
**/node_modules/**,\
**/.venv/**,\
**/__pycache__/**,\
**/*.pyc,\
**/dist/**,\
**/build/**,\
**/coverage/**,\
**/data/**,\
**/ml/models/**
  
sonar.python.version=3.11
