backend:
  replicaCount: 3

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi

frontend:
  replicaCount: 2

analytics:
  replicaCount: 2

ingress:
  enabled: true
  host: flight-delay.example.com