imagePullSecrets:
  - name: dockerhub-credentials

backend:
  replicaCount: 1

  image:
    repository: mehdibenzaied/flight-delay-backend
    tag: main-latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 5000

  containerPort: 5000
  healthPath: /health

  persistence:
    enabled: true
    size: 2Gi

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi

frontend:
  replicaCount: 1

  image:
    repository: mehdibenzaied/flight-delay-frontend
    tag: main-latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

  containerPort: 80
  healthPath: /health

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

analytics:
  replicaCount: 1

  image:
    repository: mehdibenzaied/flight-delay-backend
    tag: main-latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8050

  containerPort: 8050
  healthPath: /

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi

redis:
  replicaCount: 1

  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 6379

  persistence:
    enabled: true
    size: 1Gi

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

config:
  flaskDebug: "false"
  apiV1Str: "/api/v1"
  modelPath: "/app/ml/models/v1_model.json"
  flightDataPath: "/app/datasets/flight_data.csv"
  redisHost: redis
  redisPort: "6379"
  redisDb: "0"
  databaseUrl: "sqlite:////app/data/flight_delay.db"

ingress:
  enabled: false
  className: nginx
  host: flight-delay.local