{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flight-delay.fullname" . }}
  labels:
    {{- include "flight-delay.labels" . | nindent 4 }}

  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}

  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "flight-delay.fullname" . }}-backend
                port:
                  name: http

          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: {{ include "flight-delay.fullname" . }}-backend
                port:
                  name: http

          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flight-delay.fullname" . }}-frontend
                port:
                  name: http
{{- end }}