apiVersion: v1
kind: Service
metadata:
  name: {{ include "flight-delay.fullname" . }}-redis
  labels:
    {{- include "flight-delay.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP

  selector:
    {{- include "flight-delay.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis

  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP