grafana:
  service:
    type: NodePort
    nodePort: 30030

alertmanager:
  enabled: false

prometheus:
  service:
    type: ClusterIP

  prometheusSpec:
    retention: 2d

    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
